# Generated by Django 4.2.8 on 2024-02-06 22:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=50)),
                ('start_point', models.CharField(max_length=255)),
                ('end_point', models.CharField(max_length=255)),
                ('departure_date', models.DateField(default=datetime.date.today)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('hotel_name', models.CharField(max_length=255)),
                ('duration_of_stay', models.IntegerField(default=3)),
                ('city_image', models.ImageField(blank=True, null=True, upload_to='city_images/')),
                ('hotel_image', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('expiration_date', models.DateField()),
                ('package_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travely_packages_reservations.packagereservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
