# Generated by Django 4.2.8 on 2024-01-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travely_travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'Aller simple'), ('round_trip', 'Aller-retour')], default='one_way', max_length=20),
        ),
    ]
